version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: kfjw90as9f0we9f0jafds
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', ${WPVIP_MULTISITE} );
        define('MULTISITE', ${WPVIP_MULTISITE});
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', ${WPVIP_SITE_DOMAIN});
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);

     volumes:
       - wp_data:/var/www/html
       - ./vip-go-mu-plugins:/var/www/html/wp-content/mu-plugins

   wpcli:
     depends_on:
       - db
       - wordpress
     build:
      context: ./context
      dockerfile: ../wpcli/Dockerfile
     env_file: .env
     volumes:
       - wp_data:/var/www/html
       - ./vip-go-mu-plugins:/var/www/html/wp-content/mu-plugins

volumes:
    db_data:
    wp_data:
